# Portfolio Settings
title: "Artists Theme"
description: "Thinker // Designer // Photographer"
email: colinrubbert@gmail.com

#---- About Section ----#
#Menu Item List
menu:
- {name: About Me, url: '#about'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#Skill List
skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '8'}
- {name: IT Business Services, value: '9'}
- {name: UX Design, value: '6'}
- {name: Programming, value: '7'}


#---- Work Section ----#

projects:
- {name: TYPO International Design Talks, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: City-IN website concept, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Crispy Icons, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Fresh It Up, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: Timeline Page, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Weather Dashboard, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Stripes & Co, folder: 'proj-8', file: 'work/proj-8.html'}


# Change The Site Default Images And Content Here
logo: logo.svg
bg-img: hero-bg.jpg
avatar: face.jpg

blurb: >
  **Colin specializes in making things** for human people. Most of the things he makes are [digital interfaces](http://colinrubbert.com){:target="_blank"} and applications, but he also puts effort into crafting beautiful photography, stepping out of his comfort zone to learn new things, and builds [communities](http://community.thefirehoseproject.com){:target="_blank"} for new designers and developers.
