# Portfolio Settings
title: "Artists Theme"
description: "Thinker // Designer // Photographer"
email: colinrubbert@gmail.com

#---- About Section ----#
#Menu Item List
menu:
- {name: About Me, url: '#about'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#Skill List
skills:
- {name: Communication, value: '9'}
- {name: Organization, value: '7'}
- {name: Learning, value: '10'}
- {name: Teaching, value: '6'}
- {name: Planning, value: '8'}
- {name: IT Business Services, value: '9'}
- {name: UX Design, value: '6'}
- {name: Programming, value: '7'}


#---- Work Section ----#

projects:
- {name: Typo International Design Talks, folder: 'proj-1'}
- {name: City-IN website concept, folder: 'proj-2'}
- {name: Crisp Icons, folder: 'proj-3'}
- {name: Flat Mobile UI/UX Concept, folder: 'proj-4'}
- {name: Fresh It Up, folder: 'proj-5'}
- {name: Timeline Page, folder: 'proj-6'}
- {name: Weather Dashboard, folder: 'proj-7'}
- {name: Stripes & Co, folder: 'proj-8'}


# Change The Site Default Images And Content Here
logo: logo.svg
bg-img: hero-bg.jpg
avatar: face.jpg

blurb: <p><strong>Colin specializes in making things</strong> for human people. Most of the things he makes are <a href="http://colinrubbert.com" target="_blank">digital interfaces</a> and applications, but he also puts effort into crafting beautiful photography, stepping out of his comfort zone to learn new things, and builds <a href="http://community.thefirehoseproject.com" target="_blank">communities</a> for new designers and developers.</p>
